export const englishContent = {
    heyBeginning: 'Hey, <span style="color: #64FFDA; font-weight: bold;">Jonas</span> here.',
    createStuffText: 'I create stuff sometimes',
    homeText: 'I’m a software engineer based in Germany near Kassel. I have great interest in full-stack development with an emphasis to backend, software engineering, artifical intelligence and everything in between.',
    aboutMeText: 'I am currently working as a <span style="font-weight: bold;">Software Engineer</span> at <span style="color: #64FFDA;font-weight: bold">GLS IT Services</span> working in the Geo & Addresses team. At the same time, I am studying for a <span style="font-weight: bold;">Master of Science</span> in <span style="font-weight: bold;">Global Software Development</span> at <span style="color: #64FFDA;font-weight: bold">Hochschule Fulda</span>.',
    technologiesWorkedWithText: 'Here are some of the technologies I have worked with:',
    someMoreText: 'Some more',
    outsideOfWorkText: 'Outside of work, I’m interested in following the developments in science and tech. I also play different video games, I am interested in Fashion and I like listening to Hip Hop, Rap and Rock.',
    experienceTitleBachelor: 'Bachelor of Science Applied Computer Science Dual @ Hochschule Fulda',
    experienceBachelorText1: 'OCT 2020 - SEP 2023',
    experienceBachelorText2: 'In cooperation with GLS Germany',
    experienceBachelorText3: 'Learn basics of Computer Science in a very practical way',
    experienceBachelorText4: 'Experience with following topics: <span style="color: #64FFDA;">Programming, Software Engineering, CI/CD, IT Security, Databases and Artificial Intelligence</span>',
    experienceBachelorText5: 'Bachelor of Science Applied Computer Science finished with <span style="color: #64FFDA;">1,5</span>',
    experienceBachelorText6: 'Certificate for Cisco Certified Network Associate (CCNA)',
    experienceTitleDual: 'Dual Student Applied Computer Science @ GLS Germany',
    experienceDualText1: 'AUG 2020 - SEP 2023',
    experienceDualText2: 'Pre university development of small web application at GLS Germany',
    experienceDualText3: 'The concept of a Dual Student is that the students are during the semester fully at the university and during the semester break they work in different departments of the company',
    experienceDualText4: 'Departments I have visited and collected my expereince: <span style="color: #64FFDA">Network Operations, Test Center, Development Team for Geo & Addresses, Frontend Development in Portugal, Development Team for Geo & Addresses for Bachelor Thesis</span>',
    experienceDualText5: 'The big advantage of a Dual Student is that I was able to use my new gained knowledge directly at work',
    experienceDualText6: 'During this time I found out that I am most interested in Software Development and therefore I will continue my journey with a Masters of Scienece in Global Software Development @ Hochschule Fulda and will be working as Working Student @ GLS IT Services',
    experienceTitleMaster: 'Master of Science Global Software Development @ Hochschule Fulda',
    experienceMasterText1: 'OCT 2023 - PRESENT',
    experienceMasterText2: 'International, practice-oriented Master’s programme taught entirely in English',
    experienceMasterText3: 'Graduates are able to work in a globally distributed team on the conception and realisation of complex, distributed software systems',
    experienceMasterText4: 'Planned for 2 years with 1 semester abroad',
    experienceTitleWorkingStudent: 'Working Student Software Engineer @ GLS IT Services',
    experienceWorkingStudentText1: 'OCT 2023 - PRESENT',
    experienceWorkingStudentText2: 'Continue to work on the for Geo & Addresses Development Team',
    experienceWorkingStudentText3: 'Gain more hands-on Software Development experience',
    softwareProjectsHeadline: '/software-projects',
    softwareProjectsExplanation: 'Below are some of the projects listed that I have worked on. For more information about my projects, please contact me.',
    softwareProjectsSmallDescription: 'Small Description',
    softwareProjectsGithubLink: 'Github Link',
    softwareProjectsGitlabLink: 'Gitlab Link',
    softwareProjectsBitbucketLink: 'Bitbucket Link',
    softwareProjectsUsedTech: 'Used Technologies',
    softwareProjectTitle1: 'First Programming Project @ Hochschule Fulda',
    softwareProjectDescription1: 'A console based text adventure game simulating a typical life of a programmer',
    softwareProjectLink1: 'github.com/DerKrull/Classified (Public Repository)',
    softwareProjectUsedTech1: 'Java',
    softwareProjectTitle2: 'Development of Ludo @ Hochschule Fulda',
    softwareProjectDescription2: 'For CI/CD course - Development of Ludo (Mensch ärgere dich nicht) on the console using CI/CD techniques',
    softwareProjectLink2: 'gitlab.informatik.hs-fulda.de (Repository was removed after the course)',
    softwareProjectUsedTech2: 'Java, Jenkins',
    softwareProjectTitle3: 'Organizer App @ Hochschule Fulda',
    softwareProjectDescription3: 'As part of the Concepts of Android App Development course, we developed an Organizer App to organize your daily life including managing your calendar, your to-do list and your bank account balance',
    softwareProjectLink3: 'github.com/DerKrull/OrganizerApp (Public Repository)',
    softwareProjectUsedTech3: 'Flutter, Dart, Firebase, Material 3 Design',
    softwareProjectTitle4: 'Provision of WordPress @ Hochschule Fulda',
    softwareProjectDescription4: 'Hosting of WordPress as part of the Internet Services course using Cloud Computing techniques and Kubernetes to provide a scalable and highly available WordPress',
    softwareProjectLink4: 'gitlab.informatik.hs-fulda.de/choan312/internetservices (Private Repository)',
    softwareProjectUsedTech4: 'Terraform, OpenStack, Kubernetes, Docker, WordPress, Grafana, MariaDB',
    softwareProjectTitle5: 'Refactoring and Design Patterns @ Hochschule Fulda',
    softwareProjectDescription5: 'As part of the Software-Design course, we had to refactor an existing Java Swing code base and implement different design patterns like MVC, Proxy, Factory, Visitor and more',
    softwareProjectLink5: 'github.com/choan312/documentManagment (Private Repository)',
    softwareProjectUsedTech5: 'Java, Swing, Sonar Lint, PMD, IntelliJ',
    softwareProjectTitle6: 'Different Developments and Software Designs @ Hochschule Fulda + GLS Germany',
    softwareProjectDescription6: 'Different development tasks while working at the Geo & Addresses Development Team. Design of a custom cache for an existing microservice of the Geo & Addresses Development Team (this included a scientific paper)',
    softwareProjectLink6: 'Internal links to Bitbucket Repositories (Private Repositories)',
    softwareProjectUsedTech6: 'Java, Spring, PostgreSQL, Postman, Docker',
    softwareProjectsSomeMoreText: 'And some more...',
    contactMeHeadline: '/contact me',
    contactMeText: 'If you want to get in touch, talk to me about a project collaboration or just say hi, contact me via LinkedIn or <span style="color: #64FFDA;">send me an email!</span>',
  }

export const germanContent = {
    heyBeginning: 'Hey, <span style="color: #64FFDA; font-weight: bold;">Jonas</span> hier.',
    createStuffText: 'ich baue manchmal Dinge',
    homeText: 'Ich bin ein Software Engineer aus Deutschland, in der N<span style="font-size: 18px;">ä</span>he von Kassel. Ich habe gro<span style="font-size: 18px;">ß</span>es Interesse an Full-Stack Entwicklung mit einem Schwerpunkt auf Backend, Software Engineering, k<span style="font-size: 18px;">ü</span>nstlicher Intelligenz und allem dazwischen.',
    aboutMeText: 'Ich arbeite derzeit als <span style="font-weight: bold;">Software Engineer</span> bei <span style="color: #64FFDA;font-weight: bold">GLS IT Services</span> im Geo & Adressen Team. Gleichzeitig studiere ich im <span style="font-weight: bold;">Master of Science</span> in <span style="font-weight: bold;">Global Software Development</span> an der <span style="color: #64FFDA;font-weight: bold;">Hochschule Fulda</span>.',
    technologiesWorkedWithText: 'Hier sind einige der Technologien, mit denen ich gearbeitet habe:',
    someMoreText: 'Einige weitere',
    outsideOfWorkText: 'Neben der Arbeit interessiere ich mich f<span style="font-size:18px">ü</span>r die Entwicklungen in der Wissenschaft und Tech. Au<span style="font-size: 18px;">ß</span>erdem spiele ich verschiedene Videospiele, interessiere mich f<span style="font-size:18px">ü</span>r Mode und h<span style="font-size: 18px;">ö</span>re gerne Hip Hop, Rap und Rock.',
    experienceTitleBachelor: 'Bachelor of Science Angewandte Informatik Dual @ Hochschule Fulda',
    experienceBachelorText1: 'OKT 2020 - SEP 2023',
    experienceBachelorText2: 'In Kooperation mit GLS Germany',
    experienceBachelorText3: 'Lernen der Grundlagen der Informatik auf eine sehr praktische Art und Weise',
    experienceBachelorText4: 'Erfahrung mit folgenden Themen: <span style="color: #64FFDA;">Programmierung, Software Engineering, CI/CD, IT Security, Datenbanken und K<span style="font-size: 18px;">ü</span>nstliche Intelligenz</span>',
    experienceBachelorText5: 'Bachelor of Science Angewandte Informatik abgeschlossen mit <span style="color: #64FFDA;">1,5</span>',
    experienceBachelorText6: 'Zertifiziert als Cisco Certified Network Associate (CCNA)',
    experienceTitleDual: 'Duales Studium Angewandte Informatik @ GLS Germany',
    experienceDualText1: 'AUG 2020 - SEP 2023',
    experienceDualText2: 'Vor dem Studium Entwicklung einer kleinen Webanwendung bei GLS Germany',
    experienceDualText3: 'Das Konzept eines Dualen Studiums ist, dass die Studenten w<span style="font-size: 18px;">ä</span>hrend des Semesters vollst<span style="font-size: 18px;">ä</span>ndig an der Universit<span style="font-size: 18px;">ä</span>t sind und w<span style="font-size: 18px;">ä</span>hrend der Semesterferien in verschiedenen Abteilungen des Unternehmens arbeiten',
    experienceDualText4: 'Abteilungen, die ich besucht habe und in denen ich meine Erfahrungen gesammelt habe: <span style="color: #64FFDA">Network Operations, Test Center, Entwicklungsteam f<span style="font-size:18px">ü</span>r Geo & Adressen, Frontend Entwicklung in Portugal, Entwicklungsteam f<span style="font-size:18px">ü</span>r Geo & Adressen f<span style="font-size:18px">ü</span>r Bachelorthesis</span>',
    experienceDualText5: 'Der gro<span style="font-size: 18px;">ß</span>e Vorteil eines Dualen Studiums ist, dass ich mein neu erworbenes Wissen aus der Hochschule direkt in der Praxis anwenden konnte',
    experienceDualText6: 'W<span style="font-size: 18px;">ä</span>hrend dieser Zeit habe ich herausgefunden, dass ich mich am meisten f<span style="font-size: 18px;">ü</span>r Softwareentwicklung interessiere und deshalb werde ich meinen Werdegang mit einem Master of Science in Global Software Development @ Hochschule Fulda fortsetzen und als Werkstudent @ GLS IT Services arbeiten',
    experienceTitleMaster: 'Master of Science Global Software Development @ Hochschule Fulda',
    experienceMasterText1: 'OKT 2023 - HEUTE',
    experienceMasterText2: 'Internationaler, praxisorientierter Masterstudiengang, der vollst<span style="font-size: 18px;">ä</span>ndig in Englisch unterrichtet wird',
    experienceMasterText3: 'Absolventen sind in der Lage, in einem global verteilten Team an der Konzeption und Realisierung komplexer, verteilter Softwaresysteme zu arbeiten',
    experienceMasterText4: 'Geplant f<span style="font-size: 18px;">ü</span>r 2 Jahre mit 1 Semester im Ausland',
    experienceTitleWorkingStudent: 'Werkstudent Software Engineer @ GLS IT Services',
    experienceWorkingStudentText1: 'OKT 2023 - HEUTE',
    experienceWorkingStudentText2: 'Fortsetzung der Arbeit im Geo & Adressen Entwicklungsteam',
    experienceWorkingStudentText3: 'Mehr praktische Erfahrung in der Softwareentwicklung sammeln',
    softwareProjectsHeadline: '/software-projects',
    softwareProjectsExplanation: 'Im Folgenden sind einige der Projekte aufgelistet, an denen ich gearbeitet habe. F<span style="font-size: 18px;">ü</span>r weitere Informationen zu meinen Projekten kontaktieren Sie mich gerne.',
    softwareProjectsSmallDescription: 'Kurze Beschreibung',
    softwareProjectsGithubLink: 'Github Link',
    softwareProjectsGitlabLink: 'Gitlab Link',
    softwareProjectsBitbucketLink: 'Bitbucket Link',
    softwareProjectsUsedTech: 'Verwendete Technologien',
    softwareProjectTitle1: 'Erstes Programmierprojekt @ Hochschule Fulda',
    softwareProjectDescription1: 'Ein konsolenbasiertes Textadventure, das das typische Leben eines Programmierers simuliert',
    softwareProjectLink1: 'github.com/DerKrull/Classified (<span style="font-size: 18px;">Ö</span>ffentliches Repository)',
    softwareProjectUsedTech1: 'Java',
    softwareProjectTitle2: 'Entwicklung von Mensch <span style="font-size: 28px;">ä</span>rgere dich nicht @ Hochschule Fulda',
    softwareProjectDescription2: 'F<span style="font-size: 18px;">ü</span>r den CI/CD Kurs - Entwicklung von Mensch <span style="font-size: 18px;">ä</span>rgere dich nicht auf der Konsole mit CI/CD Techniken',
    softwareProjectLink2: 'gitlab.informatik.hs-fulda.de (Repository wurde nach dem Kurs entfernt)',
    softwareProjectUsedTech2: 'Java, Jenkins',
    softwareProjectTitle3: 'Organizer App @ Hochschule Fulda',
    softwareProjectDescription3: 'Im Rahmen des Kurses "Konzepte der Androidprogrammierung" haben wir eine Organizer-App entwickelt, um das t<span style="font-size: 18px;">ä</span>gliches Leben zu organisieren, einschlie<span style="font-size: 18px;">ß</span>lich der Verwaltung des Kalenders, der To-Do-Liste und den Bankkonten',
    softwareProjectLink3: 'github.com/DerKrull/OrganizerApp (<span style="font-size: 18px;">Ö</span>ffentliches Repository)',
    softwareProjectUsedTech3: 'Flutter, Dart, Firebase, Material 3 Design',
    softwareProjectTitle4: 'Bereitstellung von WordPress @ Hochschule Fulda',
    softwareProjectDescription4: 'Hosting von WordPress im Rahmen des Internet Services Kurses mit Cloud Computing Techniken und Kubernetes, um ein skalierbares und hochverf<span style="font-size: 18px;">ü</span>gbares WordPress bereitzustellen',
    softwareProjectLink4: 'gitlab.informatik.hs-fulda.de/choan312/internetservices (Privates Repository)',
    softwareProjectUsedTech4: 'Terraform, OpenStack, Kubernetes, Docker, WordPress, Grafana, MariaDB',
    softwareProjectTitle5: 'Refactoring und Design Patterns @ Hochschule Fulda',
    softwareProjectDescription5: 'Im Rahmen des Software-Design Kurses mussten wir einen vorhandene Java Swing Code refactoren und verschiedene Design Patterns wie MVC, Proxy, Factory, Visitor und mehr implementieren',
    softwareProjectLink5: 'github.com/choan312/documentManagment (Privates Repository)',
    softwareProjectUsedTech5: 'Java, Swing, Sonar Lint, PMD, IntelliJ',
    softwareProjectTitle6: 'Verschiedene Entwicklungen und Software Designs @ Hochschule Fulda + GLS Germany',
    softwareProjectDescription6: 'Verschiedene Entwicklungsaufgaben w<span style="font-size: 18px;">ä</span>hrend der Arbeit im Geo & Adressen Entwicklungsteam. Design eines benutzerdefinierten Caches f<span style="font-size: 18px;">ü</span>r einen vorhandenen Microservice des Geo & Adressen Entwicklungsteams (dies beinhaltete ein wissenschaftliches Paper)',
    softwareProjectLink6: 'Interne Links zu Bitbucket Repositories (Private Repositories)',
    softwareProjectUsedTech6: 'Java, Spring, PostgreSQL, Postman, Docker',
    softwareProjectsSomeMoreText: 'Und einige mehr...',
    contactMeHeadline: '/contact me',
    contactMeText: 'Wenn Sie mich kontaktieren m<span style="font-size: 18px;">ö</span>chten, mit mir <span style="font-size: 18px;">ü</span>ber eine Projektzusammenarbeit sprechen m<span style="font-size: 18px;">ö</span>chten oder einfach nur Hallo sagen m<span style="font-size: 18px;">ö</span>chten, kontaktieren Sie mich via LinkedIn oder <span style="color: #64FFDA;">senden Sie mir eine E-Mail!</span>',
  }