export const englishContent = {
    heyBeginning: 'Hey, <span style="color: #64FFDA; font-weight: bold;">Jonas</span> here.',
    createStuffText: 'I create stuff sometimes',
    homeText: 'I’m a software engineer based in Germany near Kassel. I have great interest in full-stack development with an emphasis to backend, software engineering, artifical intelligence and everything in between.',
    aboutMeText: 'I am currently working as a Software Engineer at <span style="color: #64FFDA; font-weight: bold;">GLS IT Services</span> working in the Geo & Addresses team.At the same time, I am studying for a <span style="color: #CCD6F6">Master of Science</span> in <span style="color: #CCD6F6;">Global Software Development</span> at the <span style="color: #64FFDA; font-weight: bold;">Hochschule Fulda</span>.',
    technologiesWorkedWithText: 'Here are some technologies I have been working with:',
    someMoreText: 'Some more',
    outsideOfWorkText: 'Outside of work, I’m interested in following the developments in science and tech. I also play different video games, I am interested in Fashion and I like listening to Hip Hop, Rap and Rock.',
    experienceTitleBachelor: 'Bachelor of Science Applied Computer Science Dual @ Hochschule Fulda',
    experienceBachelorText1: 'OCT 2020 - SEP 2023',
    experienceBachelorText2: 'In cooperation with GLS Germany',
    experienceBachelorText3: 'Built a strong foundation across all core areas of computer science, including programming, databases, distributed systems, software engineering, and networking.',
    experienceBachelorText4: 'Experience with following technologies: <span style="color: #64FFDA;">Java, Python, JavaScript, TypeScript, C, Spring Boot, AWS, Docker, MySQL, PostgreSQL<span>',
    experienceBachelorText5: 'Bachelor of Science Applied Computer Science finished with <span style="color: #64FFDA;">1,4</span>',
    experienceBachelorText6: 'Conducted a Bachelor thesis in cooperation with GLS IT Services GmbH on developing, deploying, and operating core microservices for address handling using Java, Spring Boot, PostgreSQL, AWS, and Kubernetes.',
    experienceBachelorText7: 'Certificate: Cisco Certified Network Associate (CCNA), showcasing in-depth knowledge of network fundamentals and operations.',
    experienceBachelorText8: 'Relevant Courses: Programming, Databases, Distributed Systems, Software Engineering, Networking.',
    experienceTitleDual: 'Dual Student Applied Computer Science @ GLS Germany',
    experienceDualText1: 'AUG 2020 - SEP 2023',
    experienceDualText2: 'Pre university development of small web application at GLS Germany',
    experienceDualText3: 'The concept of a Dual Student is that students are fully immersed in university studies during the semester and work in various company departments during semester breaks.',
    experienceDualText4: 'Departments I visited and gained experience in include: <span style="color: #64FFDA;">Network Operations, Test Center, Development Team for Geo & Addresses, Frontend Development in Portugal, Development Team for Geo & Addresses (Bachelor Thesis).<span>',
    experienceDualText5: 'A major advantage of being a Dual Student was the ability to directly apply newly acquired knowledge to real-world work scenarios.',
    experienceDualText6: 'During this time, I discovered my passion for Software Development. As a result, I pursued a Master of Science in Global Software Development at Hochschule Fulda and currently work as a Working Student at GLS IT Services.',
    experienceDualText7: 'Role Summary: During my dual study program, I combined theoretical learning with practical experience across various GLS departments. I contributed to projects such as redeveloping internal asset management tools and independently launching a core microservice for address handling.',
    experienceDualText8: 'Key Achievements:',
    experienceDualText9: 'Redeveloped internal asset management applications during a stay abroad in Portugal.',
    experienceDualText10: 'Developed a core microservice for address handling as part of my Bachelor thesis using cutting-edge technologies.',
    experienceDualText11: 'Gained experience and insights in network operations, testing, and various development teams.',
    experienceDualText12: 'Technologies Used: Java, Spring Boot, PostgreSQL, AWS, Docker, Kubernetes, Angular, Microservices, Grafana, Agile Software Development.',
    experienceTitleMaster: 'Master of Science Global Software Development @ Hochschule Fulda',
    experienceMasterText1: 'OCT 2023 - PRESENT',
    experienceMasterText2: 'International, practice-oriented Master’s programme taught entirely in English',
    experienceMasterText3: 'Graduates are able to work in a globally distributed team on the conception and realisation of complex, distributed software systems',
    experienceMasterText5: 'Led a team project to develop an internal university application for sharing digital media using agile methodologies',
    experienceMasterText6: 'Conducted research on AI hyperparameter optimization for quantized neural networks',
    experienceMasterText7: 'Led the development of a web application focusing on current trends in web application development, integrating social login, multi-factor authentication, and automated deployments',
    experienceMasterText8: 'Relevant Courses: Machine Learning, Cloud Computing, Model-Driven Development, Parallel Programming, Programming Paradigms, User Centered Development, Distributed Applications',
    experienceMasterText9: 'Technologies Used: Java, Python, JavaScript, TypeScript, C, Numpy, TensorFlow, Flutter, Docker, AWS, Azure, OpenStack, Kubernetes, Agile Software Development',
    experienceTitleWorkingStudent: 'Working Student Software Engineer @ GLS IT Services',
    experienceWorkingStudentText1: 'OCT 2023 - PRESENT',
    experienceWorkingStudentText2: 'Continue to contribute to the Geo & Addresses Development Teams success',
    experienceWorkingStudentText3: 'Leverage my newly gained knowledge directly at work to enhance software development processes',
    experienceWorkingStudentText4: 'During this time, I discovered a strong passion for Software Development. This motivated me to pursue a Master of Science in Global Software Development at Hochschule Fulda while continuing as a Working Student at GLS IT Services.',
    experienceWorkingStudentText5: 'Role Summary: As a Working Student Software Engineer, I brought extensive prior experience to the role, having already collaborated with the same team during my dual study program at GLS. With the team undergoing reorganization, I became one of the most experienced members of the development team, significantly contributing to our development efforts. My work focused on essential Geo and Address capabilities, including developing and operating multiple microservices and processes handling over 2 million daily requests, as well as migrating services to modern cloud-native platforms.',
    experienceWorkingStudentText6: 'Key Achievements:',
    experienceWorkingStudentText7: 'Developed and operated 4 microservices and 4 processes, processing ~2 million addresses daily and a web application for route planning.',
    experienceWorkingStudentText8: 'Migrated services to AWS-based cloud-native platforms using Kubernetes, Grafana, and Spring Boot (v3+).',
    experienceWorkingStudentText9: 'Integrated AI-based Address Classification to improve operational efficiency and billing processes.',
    experienceWorkingStudentText10: 'Technologies Used: Java, Spring Boot, Kubernetes, AWS, Grafana, Microservices, Docker, PostgreSQL, REST APIs, Agile Software Development, Angular.',
    experienceTitleErasmus: 'Erasmus Semester Abroad @ Linnaeus University V<span style="font-size: 18px;">ä</span>xj<span style="font-size: 18px;">ö</span>, Sweden',
    experienceErasmus1: 'AUG 2024 - JAN 2025',
    experienceErasmus2: 'Degree: Master of Science - Software Technology (Erasmus Semester Abroad)',
    experienceErasmus3: 'Completed courses in Information Visualization, Data Mining, and Systems Modeling & Simulation.',
    experienceErasmus4: 'Participated in cultural and technical exchange during an international semester in Sweden.',
    experienceErasmus5: 'Developed A1-level proficiency in Swedish through a Basic Swedish Course.',
    experienceErasmus6: 'Relevant Courses: Information Visualization, Data Mining, Systems Modeling',
    experienceErasmus7: 'Skills: Data Analysis, Visualization, Multivariate Data Techniques',
    softwareProjectsHeadline: '/software-projects',
    softwareProjectsExplanation: 'Below are some of the projects listed that I have worked on. For more information about my projects, please contact me.',
    softwareProjectsSmallDescription: 'Small Description',
    softwareProjectsGithubLink: 'Github Link',
    softwareProjectsGitlabLink: 'Gitlab Link',
    softwareProjectsBitbucketLink: 'Bitbucket Link',
    softwareProjectsUsedTech: 'Used Technologies',
    softwareProjectsLinksPapers: 'Links / Paper',
    softwareProjectTitle1: 'Hyperparameter Optimization on Quantized Neural Networks',
    softwareProjectDescription1: 'Conducted a research project focused on AI, quantization of machine learning models, and hyperparameter optimization to improve the efficiency of neural networks.',
    softwareProjectLink1: 'Contact me for details on this academic project.',
    softwareProjectUsedTech1: 'Python, TensorFlow, Scikit-learn, MQUAT, Hyperparameter Optimization, Quantization, Neural Networks, Optimizers (Adam, SGD)',
    softwareProjectTitle6: 'Internal Media Marketplace Application',
    softwareProjectDescription6: 'Led a team project to develop an internal university application for sharing digital media using agile methodologies. I was leading the team, the backend development, and the DevOps processes.',
    softwareProjectLink6: 'github.com/gihanHsFulda/GDSD-Project-Group4 (Private Repository)',
    softwareProjectUsedTech6: 'React, Node.js, Express.js, JavaScript, Azure, Material Design, MySQL, Agile Software Development, JWT',
    softwareProjectTitle2: 'To-Do Application with Focus on Current Webtechnologies',
    softwareProjectDescription2: 'Led the development of a web application focusing on current trends in web application development, integrating social login, multi-factor authentication and automated deployments.',
    softwareProjectLink2: 'Private Repository',
    softwareProjectUsedTech2: 'Flutter, Firbase, Docker, Spring Boot, Gitlab CI/CD, OAuth2, JWT, MySQL',
    softwareProjectTitle4: 'Personal Portfolio Website',
    softwareProjectDescription4: 'Built a responsive portfolio website showcasing skills and projects, incorporating Angular and Vercel for hosting.',
    softwareProjectLink4: 'github.com/choan312/choan_portfolio',
    softwareProjectUsedTech4: 'Angular, Vercel',
    softwareProjectTitle3: 'Multiple Projects @ GLS',
    softwareProjectDescription3: 'Developed and operated 4 microservices and 4 processes, processing ~2 million addresses daily and a web application. (Further details available upon request)',
    softwareProjectLink5: 'Private Repositories',
    softwareProjectUsedTech3: 'Java, Spring Boot, Kubernetes, AWS, Grafana, Microservices, Docker, PostgreSQL, REST APIs, Agile Software Development, Angular',
    softwareProjectsSomeMoreText: 'And some more...',
    contactMeHeadline: '/contact me',
    contactMeText: 'If you want to get in touch, talk to me about a project collaboration or just say hi, contact me via LinkedIn or <span style="color: #64FFDA;">send me an email!</span>',
  }

export const germanContent = {
    heyBeginning: 'Hey, <span style="color: #64FFDA; font-weight: bold;">Jonas</span> hier.',
    createStuffText: 'ich baue manchmal Dinge',
    homeText: 'Ich bin ein Software Engineer aus Deutschland, in der N<span style="font-size: 18px;">ä</span>he von Kassel. Ich habe gro<span style="font-size: 18px;">ß</span>es Interesse an Full-Stack Entwicklung mit einem Schwerpunkt auf Backend, Software Engineering, k<span style="font-size: 18px;">ü</span>nstlicher Intelligenz und allem dazwischen.',
    aboutMeText: 'Ich arbeite derzeit als <span style="font-weight: bold;">Software Engineer</span> bei <span style="color: #64FFDA;font-weight: bold">GLS IT Services</span> im Geo & Adressen Team. Gleichzeitig studiere ich im <span style="font-weight: bold;">Master of Science</span> in <span style="font-weight: bold;">Global Software Development</span> an der <span style="color: #64FFDA;font-weight: bold;">Hochschule Fulda</span>.',
    technologiesWorkedWithText: 'Hier sind einige der Technologien, mit denen ich gearbeitet habe:',
    someMoreText: 'Einige weitere',
    outsideOfWorkText: 'Neben der Arbeit interessiere ich mich f<span style="font-size:18px">ü</span>r die Entwicklungen in der Wissenschaft und Tech. Au<span style="font-size: 18px;">ß</span>erdem spiele ich verschiedene Videospiele, interessiere mich f<span style="font-size:18px">ü</span>r Mode und h<span style="font-size: 18px;">ö</span>re gerne Hip Hop, Rap und Rock.',
    
    experienceTitleBachelor: 'Bachelor of Science Angewandte Informatik Dual @ Hochschule Fulda',
    experienceBachelorText1: 'OKT 2020 - SEP 2023',
    experienceBachelorText2: 'In Zusammenarbeit mit GLS Germany',
    experienceBachelorText3: 'Aufbau eines soliden Fundaments in allen Kernbereichen der Informatik, einschlie<span style="font-size: 18px;">ß</span>lich Programmierung, Datenbanken, Verteilte Systeme, Software Engineering und Netzwerke.',
    experienceBachelorText4: 'Erfahrung mit folgenden Technologien: <span style="color: #64FFDA;font-weight: bold">Java, Python, JavaScript, TypeScript, C, Spring Boot, AWS, Docker, MySQL, PostgreSQL<span>',
    experienceBachelorText5: 'Bachelor of Science Angewandte Informatik abgeschlossen mit <span style="color: #64FFDA;">1,4</span>',
    experienceBachelorText6: 'Bachelorarbeit in Kooperation mit der GLS IT Services GmbH zum Thema Entwicklung, Deployment und Betrieb von Core-Microservices f<span style="font-size: 18px;">ü</span>r das Adresshandling mit Java, Spring Boot, PostgreSQL, AWS und Kubernetes.',
    experienceBachelorText7: 'Zertifikat: Cisco Certified Network Associate (CCNA) mit vertieften Kenntnissen <span style="font-size: 18px;">ü</span>ber Netzwerkgrundlagen und -betrieb.',
    experienceBachelorText8: 'Relevante Kurse: Programmierung, Datenbanken, Verteilte Systeme, Softwaretechnik, Netzwerktechnik.',

    experienceTitleDual: 'Duales Studium Angewandte Informatik @ GLS Germany',
    experienceDualText1: 'AUG 2020 - SEP 2023',
    experienceDualText2: 'Voruniversit<span style="font-size: 18px;">ä</span>re Entwicklung einer kleinen Webanwendung bei GLS Deutschland.',
    experienceDualText3: 'Das Konzept des Dualen Studiums besteht darin, dass die Studenten w<span style="font-size: 18px;">ä</span>hrend des Semesters voll in das Universit<span style="font-size: 18px;">ä</span>tsstudium eintauchen und in den Semesterferien in verschiedenen Unternehmensabteilungen arbeiten.',
    experienceDualText4: 'Zu den Abteilungen, die ich besucht und in denen ich meine Erfahrungen gesammelt habe, geh<span style="font-size: 18px;">ö</span>ren: <span style="color: #64FFDA">Network Operations, Test Center, Entwicklungsteam f<span style="font-size:18px">ü</span>r Geo & Adressen, Frontend Entwicklung in Portugal, Entwicklungsteam f<span style="font-size:18px">ü</span>r Geo & Adressen f<span style="font-size:18px">ü</span>r Bachelorthesis</span>',
    experienceDualText5: 'Ein gro<span style="font-size: 18px;">ß</span>er Vorteil des dualen Studiums war die M<span style="font-size: 18px;">ö</span>glichkeit, neu erworbenes Wissen direkt in der Praxis anzuwenden.',
    experienceDualText6: 'W<span style="font-size: 18px;">ä</span>hrend dieser Zeit entdeckte ich meine Leidenschaft f<span style="font-size: 18px;">ü</span>r die Softwareentwicklung. Daraufhin habe ich an der Hochschule Fulda den Master of Science in Global Software Development absolviert und arbeite derzeit als Werkstudent bei GLS IT Services.',
    experienceDualText7: 'Zusammenfassung der Aufgaben: W<span style="font-size: 18px;">ä</span>hrend meines dualen Studiums habe ich theoretisches Lernen mit praktischer Erfahrung in verschiedenen GLS Abteilungen kombiniert. Ich habe an Projekten wie der Neuentwicklung interner Asset-Management-Tools mitgewirkt und eigenst<span style="font-size: 18px;">ä</span>ndig einen zentralen Microservice f<span style="font-size: 18px;">ü</span>r das Adresshandling eingef<span style="font-size: 18px;">ü</span>hrt.',
    experienceDualText8: 'Wichtige Erfolge:',
    experienceDualText9: 'Neuentwicklung von internen Asset-Management-Anwendungen w<span style="font-size: 18px;">ä</span>hrend eines Auslandsaufenthalts in Portugal.',
    experienceDualText10: 'Entwicklung eines Kern-Microservice f<span style="font-size: 18px;">ü</span>r die Adressverarbeitung im Rahmen meiner Bachelorarbeit unter Verwendung modernster Technologien.',
    experienceDualText11: 'Erfahrungen und Einblicke in den Netzbetrieb, das Testen und verschiedene Entwicklungsteams gewonnen.',
    experienceDualText12: 'Verwendete Technologien: Java, Spring Boot, PostgreSQL, AWS, Docker, Kubernetes, Angular, Microservices, Grafana, Agile Software Development.',

    experienceTitleMaster: 'Master of Science Global Software Development @ Hochschule Fulda',
    experienceMasterText1: 'OKT 2023 - HEUTE',
    experienceMasterText2: 'Internationaler, praxisorientierter Masterstudiengang, der vollst<span style="font-size: 18px;">ä</span>ndig in Englisch unterrichtet wird',
    experienceMasterText3: 'Absolventen sind in der Lage, in einem global verteilten Team an der Konzeption und Realisierung komplexer, verteilter Softwaresysteme zu arbeiten',
    experienceMasterText5: 'Leitung eines Teamprojekts zur Entwicklung einer universit<span style="font-size: 18px;">ä</span>tsinternen Anwendung zur gemeinsamen Nutzung digitaler Medien unter Anwendung agiler Methoden',
    experienceMasterText6: 'Forschung zur KI-Hyperparameteroptimierung f<span style="font-size: 18px;">ü</span>r quantisierte neuronale Netze',
    experienceMasterText7: 'Leitung der Entwicklung einer Webanwendung mit Fokus auf aktuelle Trends in der Webanwendungsentwicklung, Integration von Social Login, Multi-Faktor-Authentifizierung und automatisierter Bereitstellung',
    experienceMasterText8: 'Relevante Kurse: Maschinelles Lernen, Cloud Computing, Modellbasierte Entwicklung, Parallele Programmierung, Programmierparadigmen, Benutzerzentrierte Entwicklung, Verteilte Anwendungen',
    experienceMasterText9: 'Verwendete Technologien: Java, Python, JavaScript, TypeScript, C, Numpy, TensorFlow, Flutter, Docker, AWS, Azure, OpenStack, Kubernetes, Agile Softwareentwicklung',
    

    experienceTitleWorkingStudent: 'Werkstudent Software Engineer @ GLS IT Services',
    experienceWorkingStudentText1: 'OKT 2023 - HEUTE',
    experienceWorkingStudentText2: 'Weiterer Beitrag zum Erfolg des Geo & Addresses Development Teams',
    experienceWorkingStudentText3: 'Mein neu erworbenes Wissen direkt bei der Arbeit einsetzen, um die Softwareentwicklungsprozesse zu verbessern',
    experienceWorkingStudentText4: 'W<span style="font-size: 18px;">ä</span>hrend dieser Zeit entdeckte ich eine starke Leidenschaft f<span style="font-size: 18px;">ü</span>r die Softwareentwicklung. Dies motivierte mich, einen Master of Science in Global Software Development an der Hochschule Fulda zu absolvieren und gleichzeitig als Werkstudent bei GLS IT Services zu arbeiten.',
    experienceWorkingStudentText5: 'Zusammenfassung der Rolle: Als Werkstudent f<span style="font-size: 18px;">ü</span>r Softwareentwicklung bringe ich umfangreiche Vorerfahrungen mit, da ich bereits w<span style="font-size: 18px;">ä</span>hrend meines dualen Studiums an der GLS mit demselben Team zusammengearbeitet habe. Durch die Umstrukturierung des Teams wurde ich zu einem der erfahrensten Mitglieder des Entwicklungsteams und leistete einen wichtigen Beitrag zu unseren Entwicklungsbem<span style="font-size: 18px;">ü</span>hungen. Meine Arbeit konzentrierte sich auf wesentliche Geo und Address F<span style="font-size: 18px;">ä</span>higkeiten, einschlie<span style="font-size: 18px;">ß</span>lich der Entwicklung und des Betriebs mehrerer Microservices und Prozesse, die t<span style="font-size: 18px;">ä</span>glich <span style="font-size: 18px;">ü</span>ber 2 Millionen Anfragen bearbeiten, sowie der Migration von Services auf moderne Cloud-native Plattformen.',
    experienceWorkingStudentText6: 'Wichtige Erfolge',
    experienceWorkingStudentText7: 'Entwicklung und Betrieb von 4 Microservices und 4 Prozessen, die t<span style="font-size: 18px;">ä</span>glich ~2 Millionen Adressen verarbeiten, sowie einer Webanwendung f<span style="font-size: 18px;">ü</span>r die Routenplanung.',
    experienceWorkingStudentText8: 'Migration von Diensten auf AWS-basierte Cloud-native Plattformen unter Verwendung von Kubernetes, Grafana und Spring Boot (v3+).',
    experienceWorkingStudentText9: 'Integrierte KI-basierte Adressklassifizierung zur Verbesserung der betrieblichen Effizienz und der Abrechnungsprozesse.',
    experienceWorkingStudentText10: 'Verwendete Technologien: Java, Spring Boot, Kubernetes, AWS, Grafana, Microservices, Docker, PostgreSQL, REST APIs, Agile Software Development, Angular.',
    
    experienceTitleErasmus: 'Erasmus Auslandssemester @ Linnaeus University V<span style="font-size: 18px;">ä</span>xj<span style="font-size: 18px;">ö</span>, Sweden',
    experienceErasmus1: 'AUG 2024 - JAN 2025',
    experienceErasmus2: 'Studiengang: Master of Science - Softwaretechnologie (Erasmus-Auslandssemester)',
    experienceErasmus3: 'Absolvierte Kurse in Informationsvisualisierung, Data Mining und Systemmodellierung & Simulation.',
    experienceErasmus4: 'Teilnahme am kulturellen und technischen Austausch w<span style="font-size: 18px;">ä</span>hrend eines Auslandssemesters in Schweden.',
    experienceErasmus5: 'Entwicklung von Schwedischkenntnissen auf A1-Niveau durch einen Schwedisch-Grundkurs.',
    experienceErasmus6: 'Relevante Kurse: Informationsvisualisierung, Data Mining, Systemmodellierung',
    experienceErasmus7: 'Fertigkeiten: Datenanalyse, Visualisierung, multivariate Datentechniken',

    softwareProjectsHeadline: '/software-projects',
    softwareProjectsExplanation: 'Nachstehend sind einige der Projekte aufgef<span style="font-size: 18px;">ü</span>hrt, an denen ich gearbeitet habe. F<span style="font-size: 18px;">ü</span>r weitere Informationen <span style="font-size: 18px;">ü</span>ber meine Projekte kontaktieren Sie mich bitte.',
    softwareProjectsSmallDescription: 'Kurze Beschreibung',
    softwareProjectsGithubLink: 'Github Link',
    softwareProjectsGitlabLink: 'Gitlab Link',
    softwareProjectsBitbucketLink: 'Bitbucket Link',
    softwareProjectsUsedTech: 'Verwendete Technologien',
    softwareProjectsLinksPapers: 'Links / Paper',
    softwareProjectTitle1: 'Hyperparameter-Optimierung auf quantisierten neuronalen Netzen',
    softwareProjectDescription1: 'Durchf<span style="font-size: 18px;">ü</span>hrung eines Forschungsprojekts mit Schwerpunkt auf KI, Quantisierung von Modellen des maschinellen Lernens und Optimierung der Hyperparameter zur Verbesserung der Effizienz neuronaler Netze.',
    softwareProjectLink1: 'Kontaktieren Sie mich f<span style="font-size: 18px;">ü</span>r weitere Informationen zu diesem akademischen Projekt.',
    softwareProjectUsedTech1: 'Python, TensorFlow, Scikit-learn, MQUAT, Hyperparameter Optimization, Quantization, Neural Networks, Optimizers (Adam, SGD)',

    softwareProjectTitle6: 'Interne Medienmarktplatz-Anwendung',
    softwareProjectDescription6: 'Ich leitete ein Teamprojekt zur Entwicklung einer internen Universit<span style="font-size: 18px;">ä</span>tsanwendung f<span style="font-size: 18px;">ü</span>r die gemeinsame Nutzung digitaler Medien unter Verwendung agiler Methoden. Ich habe das Team, die Backend-Entwicklung und die DevOps-Prozesse geleitet.',
    softwareProjectLink6: 'github.com/gihanHsFulda/GDSD-Project-Group4 (Private Repository)',
    softwareProjectUsedTech6: 'React, Node.js, Express.js, JavaScript, Azure, Material Design, MySQL, Agile Software Development, JWT',

    softwareProjectTitle2: 'To-Do-Anwendung mit Fokus auf aktuelle Webtechnologien',
    softwareProjectDescription2: 'Ich leitete die Entwicklung einer Webanwendung, die sich auf die aktuellen Trends in der Entwicklung von Webanwendungen konzentriert und Social Login, Multi-Faktor-Authentifizierung und automatisierte Bereitstellungen integriert.',
    softwareProjectLink2: 'Private Repository',
    softwareProjectUsedTech2: 'Flutter, Firbase, Docker, Spring Boot, Gitlab CI/CD, OAuth2, JWT, MySQL',

    softwareProjectTitle3: 'Mehrere Projekte @ GLS',
    softwareProjectDescription3: 'Entwicklung und Betrieb von 4 Microservices und 4 Prozessen, Verarbeitung von ~2 Millionen Adressen t<span style="font-size: 18px;">ä</span>glich und einer Webanwendung. (Weitere Details sind auf Anfrage erh<span style="font-size: 18px;">ä</span>ltlich)',
    softwareProjectLink3: 'Private Repository',
    softwareProjectUsedTech3: 'Java, Spring Boot, Kubernetes, AWS, Grafana, Microservices, Docker, PostgreSQL, REST APIs, Agile Software Development, Angular',

    softwareProjectTitle4: 'Personal Portfolio Website',
    softwareProjectDescription4: 'Erstellung einer responsiven Portfolio-Website zur Pr<span style="font-size: 18px;">ä</span>sentation von F<span style="font-size: 18px;">ä</span>higkeiten und Projekten unter Einbeziehung von Angular und Vercel f<span style="font-size: 18px;">ü</span>r das Hosting.',
    softwareProjectLink4: 'github.com/choan312/choan_portfolio',
    softwareProjectUsedTech4: 'Angular, Vercel',

    softwareProjectTitle5: 'Personal Portfolio Website',
    softwareProjectDescription5: 'Erstellung einer responsiven Portfolio-Website zur Pr<span style="font-size: 18px;">ä</span>sentation von F<span style="font-size: 18px;">ä</span>higkeiten und Projekten unter Einbeziehung von Angular und Vercel f<span style="font-size: 18px;">ü</span>r das Hosting.',
    softwareProjectLink5: 'github.com/choan312/choan_portfolio',
    softwareProjectUsedTech5: 'Angular, Vercel',

    softwareProjectsSomeMoreText: 'Und einige mehr...',
    contactMeHeadline: '/contact me',
    contactMeText: 'Wenn Sie mich kontaktieren m<span style="font-size: 18px;">ö</span>chten, mit mir <span style="font-size: 18px;">ü</span>ber eine Projektzusammenarbeit sprechen m<span style="font-size: 18px;">ö</span>chten oder einfach nur Hallo sagen m<span style="font-size: 18px;">ö</span>chten, kontaktieren Sie mich via LinkedIn oder <span style="color: #64FFDA;">senden Sie mir eine E-Mail!</span>',
  }